language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.8.7
  - 1.9.3
  - 1.9.2

env:
  - TEST_SUITE=features
  - TEST_SUITE=controllers
  - TEST_SUITE=helpers
  - TEST_SUITE=models
  - TEST_SUITE=routing
  - TEST_SUITE=views

script: bundle exec rspec spec/$TEST_SUITE/*